name: MUHAMMAD ALZUHAIRY

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Find and Replace

        uses: jacobtomlinson/gha-find-replace@master

        with:

          find: "GROUPJMTHON"

          replace: "VV_Rk"

      - name: Create Pull Request

        uses: stefanzweifel/git-auto-commit-action@v4

        with:

          commit_message: 'تلي : RR7PP'

          commit_options: '--no-verify'

          repository: .

          commit_user_name: MATREX1X

          commit_user_email: roz@emtg.in
